<link rel="stylesheet" href="<?php echo base_url() ?>assets/css/pages/terms.css">
<section id="big_header"> 
    <div class="white-box">
	  
	<h1 style="" class="text-center title">Terms & Conditions</h1>
		
<p>The following Terms of Service, which include the Privacy Policy, IP Policy, and any guideline, policy or content displayed on the Website, are a legally binding contractual agreement between you (“User, “you,” “your”) and Websoft, LLC. d/b/a Winjob.com (“Winjob.com,” “we,” “us”) (hereinafter collectively referred to as the “Terms of Service”).  By visiting or using the services available from the domain and sub-domains of www.winjob.com (the “Website”), you agree to be legally bound by these Terms of Service. We reserve the right to revise these Terms of Service and all linked information from time to time in our sole discretion by updating this posting or any linked information. Unless otherwise provided in such revision, the revised terms will take effect when they are posted.</p>
<b>1.REGISTRATION</b>
<p>A. Eligibility. To access our Services through our Website, you must be a legal entity, or an individual of eighteen (18) years of age or older who can form legally binding contracts. To become a Registered User, you must accept all of the terms and conditions in, LLC by reference in, and linked to, these Terms of Service. By becoming a Registered User, you agree to: (1) abide by the Terms of Service and the processes, procedures, and guidelines described throughout the Website; (2) be financially responsible for your use of the Website and the purchase or delivery of services; and (3) perform your obligations as specified by any Project Agreement that you accept, unless such obligations are prohibited by law or by the Terms of Service. Winjob.com reserves the right, in its sole discretion, to refuse, suspend, or terminate Services to anyone.</p>
<b>B. Registration.</b>
<p>To become a Registered User and to access Services you must register for an Account. You agree to provide true, accurate and complete information as prompted by the registration form and all forms you access on the Website, and to update this information to maintain its truthfulness, accuracy and completeness.</p>
<b>C.  Accounts and Profiles.</b>
<p>General. Once you have registered with the Website as a Registered User, the Website will create your Account with Winjob.com and associate it with an account number. You may create a profile under your Account,
Username and Password. During registration, you will be asked to choose a username and password for the Account. As a Registered User, you agree and you are entirely responsible to safeguard and maintain the confidentiality of the username and password you use to access this Website. You authorize Winjob.com to assume that any person using the Website with your username and password is you or is authorized to act for you. You agree to notify us immediately if you suspect any unauthorized use of the Account.</p>
<b>2.Information Collection</b>
<p>Winjob.com is an online marketplace that connects clients & businesses with freelancers. When you visit Winjob.com you provide two types of informations: personal information-that you knowingly choose to disclose to Winjob.com and the information collected by Winjob.com as you interact with www.Winjob.com (the “site”).</p> 

<p>When you register with Winjob.com as a Freelancer or as an Employer, you provide certain personal information, including, your name, your email address and your address. Additionally, when you establish your profile as a Freelancer or as an Employer you will provide information relating to your skills, experience, education level, compensation, work availability, geographic region and self-evaluation. Such information does not identify the specificity of the individual member. Employers are only shown basic information about freelancer and can communicate to them only using the Winjob.com Platform. </p>

<p>When you enter the website, Winjob.com collects your IP address and your location (If you allow). This information is gathered from all Winjob.com visitors. In addition, Winjob.com stores certain information from your browser using “cookies.” A cookie is a piece of data stored on the user’s computer tied to information about the user. Winjob.com uses session ID cookies to confirm that users are logged in. These cookies terminate once the user closes the browser. By default, Winjob.com uses a persistent cookie that stores your login ID (but not your password) to make it easier for you to login when you return to the Website. Winjob.com members must have cookies enabled on their browsers. Note, Cookie preferences are set within each browser’s Internet options/preferences</p>

<b>3.RELATIONSHIPS</b>

<p>A.  Employer and Freelancer.
1. Project Agreement. The engagement, contracting and management of a project are between an Employer and a Freelancer. Upon acceptance of a quote, the Employer agrees to purchase, and the Freelancer agrees to deliver, the services and related deliverables in accordance with the following agreements: (a) the agreement between Employer and Freelancer including the Project Bid, Project Description, and other terms and conditions as communicated between Employer and Freelancer on the Website or otherwise, (b) these Terms of Service, and (c) any other content uploaded to the Website by Winjob.com (collectively, the “Project Agreement”). You agree not to enter into any contractual provisions in conflict with these Terms of Service. Any provision of a Project Agreement in conflict with these Terms of Service is void. Employer is responsible for managing, inspecting, accepting and paying for satisfactory services and deliverables in accordance with the Project Agreement in a timely manner. Freelancer is responsible for the performance and quality of the services in accordance with the Project Agreement in a timely manner. Employer and Freelancer each covenants and agrees to act with good faith and fair dealing in performance of the Project Agreement.</p>

<b>2. Independence.</b>
 <p>Employer and Freelancer each acknowledges and agrees that their relationship is that of independent contractors. The Freelancer shall perform services as an independent contractor and nothing in these Terms of Service shall be deemed to create a partnership, joint venture, agency, or employer-employee relationship between Freelancer and Employer or between Winjob.com and any Employer or Freelancer.</p>
<b>B. Registered Users and Winjob.com</b>

<b>1. General.</b>
<p>Winjob.com is not a party to the dealing, contracting and fulfillment of any Project between an Employer and a Freelancer. Winjob.com has no control over and does not guarantee the quality, safety or legality of any services performed or deliverables created, advertised, the truth or accuracy of project listings, the qualifications, background, or abilities of Registered Users, the ability of Freelancers to perform services, the ability of Employers to pay for services, or that an Employer or Freelancer can or will actually complete a Project. Winjob.com is not responsible for and will not control the manner in which a Freelancer operates and is not involved in the hiring, firing, discipline or working conditions of the Freelancer. All rights and obligations for the purchase and sale of services or other deliverables are solely between an Employer and a Freelancer. Winjob.com will not provide any Freelancer with any materials or tools to complete any Project. Employers and Freelancers must look solely to the other for enforcement and performance of all the rights and obligations arising from Project Agreements and any other terms, conditions, representations, or warranties associated with such dealings.</p>

<b>2. Third-Party Beneficiary of Project Agreement.</b>
<p>Employer and Freelancer each acknowledges and agrees that the value, reputation, and goodwill of the Website depend on their performance of their covenants and agreements as set forth in their Project Agreement. Employer and Freelancer therefore appoint Winjob.com as a third-party beneficiary of their Project Agreement for purposes of enforcing the obligations owed to, and the benefits conferred on, Winjob.com by these Terms of Service. Employers and Freelancers further agree that Winjob.com has the right to take such actions with respect to the Project Agreement or their Accounts, including without limitation, suspension, termination, or any other legal actions, as Winjob.com in its sole discretion deems necessary to protect the value, reputation, and goodwill of the Website.</p>

<b>3. Taxes.</b> 
<p>Registered Users are responsible for payment and reporting of any taxes. Other than in connection with the 1099 Service, Winjob.com is not obligated to determine the applicability of any taxes or to remit, collect or report any such applicable taxes, unless otherwise agreed to by both parties pursuant to the terms of any provision of tax services provided to you by Winjob.com. You agree that you will abide by any and all applicable state and federal tax statutes, regulations and common law. In the event Winjob.com receives a notice of non-compliance with any such statute, regulation or common law, including, without limitation, an Internal Revenue Service Levy, Winjob.com will deem such receipt a breach of this section and will suspend your Account until Winjob.com received an Internal Revenue Service Release.</p>

<b>4.	Winjob.COM FEES</b>

<b>1. Employer Payment Processing Fee.</b>
If an Employer pays a Freelancer with a credit card or PayPal account, a Payment Processing Fee will be charged to the Employer as described here.</p>
<b>2. Freelancer Transfer Method Fee.</b>
<p>If, upon a Freelancer’s request, funds are to be disbursed via check or a wire transfer, a Freelancer Transfer Method Fee will be charged to the Freelancer as described here. Transfers made through use of automated clearinghouse, Paypal and Payoneer debit card methods will incur no such fee.</p>
<b>3. Dispute Resolution Service Fee. </b>
<p>For use of Dispute Resolution Services, irrespective of the nature of resolution and any resulting disbursements, Winjob.com charges a Dispute Resolution Service Fee, equal to the greater of twenty-five dollars ($25.00) and five percent (5%) of the total amount paid by an Employer to Winjob.com for the applicable project to which such payment relates.</p>


<b>6. Payment Terms</b>

<b>5. 1. Service Fee</b>
<p>When funds related to an Engagement are otherwise released to a Contractor as required by the applicable Instructions, Winjob will credit the Contractor’s account and then deduct and disburse to Winjob Ten Percent (10%) of the Contractor’s Fee (whether a Fixed or Variable Fee Engagement) in consideration of Winjob’s creation, hosting, and maintenance of the Website for Contractor’s use (the "Service Fee"). If Contractor elects disbursement in a currency other than U.S. Dollars, Winjob will add Winjob's conversion fee of One and a Half Percent (1. 5%) to the spot rate quoted by its foreign exchange vendor and credit that amount to Winjob.</p>

<b>5. 2. Disbursements to Contractors</b>
<p>For Variable Fee Engagements, the Contractor’s Fee becomes payable to Contractors following the expiration of the Dispute Period and the Security Period, unless paid sooner by the Client. For Fixed Fee Engagements, the Contractor’s Fees become payable to Contractors following the expiration of the Security Period. The security period begins after Client accepts work submitted by Contractor by clicking the "Make a Payment" button.
Notwithstanding any other provision in this Agreement or the Instructions, and except as prohibited by applicable law, if we determine in our sole discretion that you have violated the conditions and restrictions of the Website or this Agreement, Winjob may withhold the disbursement of the Contractor’s Fees. Additionally, Winjob may also withhold the disbursement of the Contractor’s Fees if:
(a) we require additional information, such as Contractor's tax information, government-issued identification, address, or date of birth;
(b) we have reason to believe the Contractor’s Fees may be subject to dispute or chargeback;
(c) we suspect fraud;
(d) we believe there are reasonable grounds for insecurity with respect to the performance of obligations under an Engagement, this Agreement, or other Terms of Service;
(e) we deem it necessary in connection with any investigation; or (f) we are required to do so by applicable law.
In cases of fraud, abuse, or violation of this Agreement, Winjob reserves the right to revoke any payments and instruct Winjob to, and you hereby acknowledge that Winjob will have the right to, withhold and/or reclaim from Winjob all Contractor’s Fees due to Contractor (not just the Contractor’s Fees from the Engagement(s) under investigation). In addition, we reserve the right to seek reimbursement from you, and you will reimburse us, if we suspect fraud or criminal activity associated with your payment, withdrawal, or Engagement; if we discover erroneous or duplicate transactions; or if we have supplied our services in accordance with this Agreement yet we receive any chargeback from the credit card company, bank, PayPal or other payment method as used by you, or as used by your Client if you are a Contractor. You agree that we have the right to obtain such reimbursement by instructing Winjob to (and Winjob will have the right to) charge an applicable account, and any other accounts you hold with us, offsetting any amounts determined to be owing to us, deducting amounts from future payments or withdrawals, charging your credit card, or obtaining reimbursement from you by any other lawful means. Failure to pay for reimbursements of chargebacks is cause for termination of the applicable account.</p>

<b>5. 3. Non-payment</b>
<p>If Client fails to pay the Contractor’s Fee or any other amounts due under this Agreement, whether by cancelling Client's credit or debit card, initiating an improper chargeback, or any other means, Winjob may suspend or close Client's Account and revoke Client's access to the Website, including Client's ability to use the Website to process any additional payments or obtain any additional Contractor Services. Without limiting other available remedies, Client must pay Winjob upon demand for amounts owed under this Agreement, plus interest on the outstanding amount at the lesser of one and one-half percent (1. 5%) per month or the maximum interest allowed by applicable law, plus attorneys' fees and other costs of collection to the extent permitted by applicable law. To the extent permitted by applicable law, Winjob, at its discretion, may set off amounts due against other amounts received from or held by Winjob for Client, make appropriate reports to credit reporting agencies and law enforcement authorities, and cooperate with credit reporting agencies and law enforcement authorities in any resulting investigation and/or prosecution.</p>

<b>5. 4. No Return of Funds/No Refunds</b>
<p>Client acknowledges and agrees that Winjob will charge Client's designated Payment Method for the Contractor’s Fees:</p>
<p>(a) for Fixed Fee Engagements, upon Client's acceptance of the Contractor Services, and
(b) for Hourly Rate Contacts, on the Monday after the week in which work was performed. Therefore, and in consideration of the Website provided by Winjob, Client agrees that once Winjob charges Client's designated Payment Method for the Contractor’s Fees as provided in this Agreement, the charge is non-refundable, except as otherwise required by applicable law. Client also acknowledges and agrees that Section 8. 3 of this Agreement provides a dispute resolution process as a way for Client resolve disputes. To the extent permitted by applicable law, Client therefore agrees not to ask its credit card company, bank, or other Payment Method provider to charge back any Contractor’s Fees or other Fees charged pursuant to this Agreement for any reason. A chargeback in breach of the foregoing obligation is a material breach of this Agreement. If Client initiates a chargeback in violation of this Agreement, Client agrees that Winjob or Winjob may dispute or appeal the chargeback and institute collection action against Client.</p>

<b>5. 5. Formal Invoices and Taxes</b>
<p>Winjob will have no responsibility for determining the necessity of or for issuing any formal invoices, or for determining, remitting, or withholding any taxes applicable to the Contractor’s Fees. Contractor will be solely responsible for determining whether it is required by applicable law to issue any formal invoices for the Contractor’s Fees and for issuing any invoices so required. Contractor will also be solely responsible for determining:</p>
<p>(a) whether Contractor or Winjob is required by applicable law to remit to the appropriate authorities any value added tax or any other taxes or similar charges applicable to the Contractor’s Fees and remitting any such taxes or charges to the appropriate authorities on behalf of itself or Winjob, as appropriate; and
(b) whether Winjob is required by applicable law to withhold any amount of the Contractor’s Fees and for notifying Winjob of any such requirement and indemnifying Winjob (either by Winjob, at our sole discretion, offsetting the relevant amount against a future payment of Contractor’s Fees to Contractor or Contractor reimbursing Winjob for the applicable amount) for any requirement to pay any withholding amount to the appropriate authorities (including penalties and interest). In the event of an audit of Winjob, You hereby agree to promptly cooperate with Winjob and provide copies of Your tax returns and other documents as may be reasonably requested for purposes of such audit, including but not limited to records showing You are engaged in an independent business as represented to Winjob.</p>

<b>5. 6. Payment Methods</b>
<p>In order to use certain Website, Client must provide account information for at least one valid Payment Method. The Website makes the following methods of payment available: credit cards, debit cards, and PayPal.
Client hereby authorizes Winjob, its Affiliates, and Winjob to run credit card authorizations on all credit cards provided by Client, to store credit card and banking details as Client's method of payment for Services, and to charge Client's credit card (or any other form of payment authorized by Winjob or mutually agreed to between Client and Winjob). Credit cards and PayPal accounts in most countries will be charged by Winjob. Notwithstanding the foregoing, credit cards and PayPal accounts in Australia, Canada, the Eurozone, and the United Kingdom will be charged by Winjob LLC, an Ireland registered company which is an Affiliate of Winjob, Winjob LLC may, in their sole discretion, deviate from its typical billing cycle for Variable Fee Engagements and charge Client for any and all Time Logs at any time.
When a Client authorizes the payment of the a Contractor’s Fee for a Fixed Fee Engagement on the Website, Client automatically and irrevocably authorizes and instructs Winjob LLC to charge Client's Payment Method for the Contractor’s Fees. When Client approves or is deemed to have approved a Time Log for a Variable Fee Engagement, Client automatically and irrevocably authorizes and instructs Winjob to charge Client's Payment Method for the Contractor’s Fees. Winjob may, in its sole discretion, deviate from the typical billing cycle for Variable Fee Engagements and charge Client for any and all Time Logs at any time.</p>

<p>By providing Payment Method information through the Website, Client represents, warrants, and covenants that:</p>
<p>(a) Client is legally authorized to provide such information to us;
(b) Client is legally authorized to perform payments using the Payment Method(s); and
(c) such action does not violate the terms and conditions applicable to Client's use of such Payment Method(s) or applicable law. When Client authorizes a payment using a Payment Method via the Website, Client represents, warrants, and covenants that there are sufficient funds or credit available to complete the payment using the designated Payment Method. To the extent that any amounts owed under this Agreement cannot be collected from Client's Payment Method(s), Client is solely responsible for paying such amounts by other means.
We reserve the right to seek reimbursement from you, and you will reimburse us, if we suspect fraud or criminal activity associated with your payment, withdrawal, or Engagement, if we discover erroneous or duplicate transactions, or if we have supplied our services in accordance with this Agreement yet we receive any chargeback from the credit card company, bank, PayPal or other payment method as used by you, or as used by your Client if you are a Contractor. You agree that we have the right to obtain such reimbursement by instructing Winjob charge an applicable account, and any other accounts you hold with us, offsetting any amounts determined to be owing, deducting amounts from future payments or withdrawals, charging your credit card, or obtaining reimbursement from you by any other lawful means. Failure to pay for reimbursements of chargebacks is cause for termination of the applicable account.</p>

<b>5. 7. US Dollars and Foreign Currency Conversion</b>
<p>The Website and the Contractor’s Fees are calculated and determined in US Dollars. If Client's Payment Method is denominated in a currency other than US Dollars and requires currency conversion to make payments in US Dollars, the Website may display foreign currency conversion rates Winjob or other Affiliates currently make available to convert supported foreign currencies to US Dollars. These foreign currency conversion rates adjust regularly based on market conditions. Please note that the wholesale currency conversion rates at which we obtain foreign currency will usually be different than the foreign currency conversion rates offered on the Website. Client, at its sole discretion and risk, may authorize the charge of its Payment Method in a supported foreign currency and the conversion of the payment to US Dollars at the foreign currency conversion rate displayed on the Website. A list of supported foreign currencies is available on the Website. If foreign currency conversion is required to make a payment in US Dollars and either Winjob or another Affiliate does not support the foreign currency or Client does not authorize the conversion of such payment at the foreign currency conversion rate displayed on the Website, Winjob an Affiliate will charge Client's Payment Method in US Dollars and Client's Payment Method provider will convert the payment at a foreign currency conversion rate selected by Client's Payment Method provider. Client's Payment Method provider may also charge fees directly to the Payment Method used to fund a cross-border payment even when no currency conversion is involved, which is outside of Winjob’s control. Client's authorization of a payment using a foreign currency conversion rate displayed on the Website is at Client's sole risk. We are not responsible for currency fluctuations that occur when billing or crediting a Payment Method denominated in a currency other than US Dollars. We are not responsible for currency fluctuations that occur when receiving or sending payments via wire transfer, check or automated clearinghouse to and from accounts.</p>

<b>5. 8. Limited Payment Protection</b>
<p>In the rare event that a Client does not make payment for legitimate services performed by a Contractor, Winjob will provide limited payment protection to the Contractor ("Payment Protection") as a membership benefit to foster fairness, reward loyalty, and encourage the Contractor to continue to use the Website for their business needs.</p>

<p>Winjob only provides Payment Protection to Contractors working pursuant to Variable Fee Engagements and only if all of the following criteria are met:
(a) Client has a verified Payment Method,
(b) the time represented is captured online using the Winjob Team Software,
(c) the Contractor Services performed and recorded in the Time Log pertain directly to the Engagement, and
(d) each Time Log is annotated with detailed descriptions of the Contractor Services performed, demonstrating Engagement compliance. Winjob determines whether the foregoing criteria have been met at our sole discretion. Without limiting the foregoing, Payment Protection does not apply to:
(a) a Contractor or Client’s violation of this Agreement,
(b) if an Engagement violates this Agreement,
(c) Contractors that are aware of or complicit in another Winjob’s violation of this Agreement, or
(z) suspected (in Winjob's sole discretion) or actual fraudulent activities or abuse of this Payment Protection.</p>

<b>6. Engagement Terms Between Client And Contractor</b>
<p>Unless otherwise agreed to in a writing signed by both Client and Contractor, the terms and conditions of the Engagement that a Contractor enters directly with a Client when the Contractor agrees to provide Services to the Client are as set forth in this Section. Client and Contractor may not agree to any other terms and conditions that affect the rights or responsibilities of Winjob, its Affiliates. Winjob is not a party to any Engagement between Winjobs, except as an intended third-party beneficiary as described further below.</p>

<b>6. 1. Services</b>
<p>Contractor will perform the Contractor Services in a professional and workmanlike manner and will timely deliver any agreed upon Work Product. The manner and means of performing the Contractor Services will be determined and controlled by Contractor.</p>

<b>6. 2. Client Payments and Billing</b>
<p>For Variable Fee Engagements, Client is billed for Contractor’s Fees on a weekly basis. For Fixed Fee Engagements, Client is billed immediately upon accepting an offer.</p>

<b>6. 3. Dispute Resolution</b>
<p>With respect to each Engagement, you agree to abide by the Dispute Resolution Procedures as promulgated by Winjob.</p>

<b>6. 4. Termination of an Engagement</b>
<p>Under Variable Fee Engagements: Either Client or Contractor has the right to terminate the Engagement after providing any required notice, or immediately without notice on or after the end date specified in the Engagement terms and/or upon completion of the Contractor Services. In the event of a material breach of the Engagement, the non-breaching party may terminate the Engagement immediately without notice. Client and Contractor may mutual agree to terminate an Engagement at any time. Except as required by law, Client remains obligated to pay the Contractor’s Fees for any Contractor Services provided prior to termination of the Hourly Rate Contract.
Under Fixed Fee Engagements: Once a Client's Payment Method has been charged to fund the the Engagement, absent a full refund to Client by Contractor, the Engagement does not terminate until the Contractor Services are completed. However, Client and Contractor may mutually agree to terminate a Fixed Fee Engagement at any time. Furthermore, in the event of a material breach of the Fixed Fee Engagement, the non-breaching party may immediately terminate the Fixed Fee Engagement without notice. If a Fixed Fee Engagement is terminated, Client does not have the right to recover any payments already released to Contractor for the Engagement.</p>

<b>7.Security</b>
<p>Winjob.com takes industry standard protocols and technology to protect registered user information. </p>

<p>Winjob.com also protects registered user information offline. All registered user information is restricted within our offices. Servers used to store personally identifiable information are housed in a secure, supervised environment. In addition, only Winjob.com employees who need specific information to perform a task are granted access to personally identifiable information.</p>
<b>8.Mandatory Communications</b>
<p>Winjob.com sends all newly registered users a welcome email to verify their email addresses. At times, Winjob.com sends service announcements to its registered Employers and Freelancers. Registered Users cannot unsubscribe from service announcements that discuss upcoming changes that affect their Winjob.com accounts. In addition, we communicate with registered members via personal emails or phone calls to provide requested services.</p>
<b>9.Optional Communications</b>
<p>Registered users receive monthly e-newsletters containing information on Winjob.com products, services and announcements. Occasionally, registered users receive e-postcards that highlight special Winjob.com announcements and features. Registered users can opt-out of the above listed communications. Please see our Choice/Opt-out section below.</p>
<b>10.Choice/Opt-out</b>
<p>Upon registration, users can opt-out of Winjob.com’s optional communications. Additionally, registered users can, at any time, modify their Winjob.com email (service announcement) preferences by updating their account information.</p>
<b>11.Notification of Changes</b>
<p>Winjob.com reserves the right to modify this privacy policy at any time, so please review it frequently. If Winjob.com alters its Privacy Policy, it will promptly post all changes in the Employer and Freelancer Announcement areas. By continuing to use Winjob.com after changes have been made to this policy, you are consenting to the changes.</p>


		
</section><!-- big_header-->
